site_name: Starter DS Project Repo
site_url: https://mydomain.org/mysite
repo_url: https://github.com/PhiQus-DS/pq-starter-ds-project
theme:
  name: material
  locale: en
  color_mode: auto
  user_color_mode_toggle: true
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_source: false
            show_root_members_full_path: true

nav:
  - Home: index.md
  - Reference:
    - reference/index.md
    - reference/deleteme.md
